### PR TITLE
Fix CSS build process

### PR DESCRIPTION
**Pull request by danbee**
The PR I created to update to Webpack 5 and NodeJS 20 broke the CSS build process. This fixes it, and moves it out of Webpack and uses Dart Sass directly to build the CSS.

### CODE REVIEW

**Comment by jadefish** [comment]
locally I'll iterate with `webpack --watch`. does moving CSS generation out of webpack break this workflow? is there still a way to watch for changes and continually recompile JS and CSS?

**Comment by danbee** [comment]
@jadefish Good call! Let me look into that.

**Comment by danbee** [comment]
@jadefish I've added a new script and `Procfile`. So now you can run `scripts/watch` and it will run both the Webpack JS compilation and SASS compilation with a `--watch` parameter.

**Comment by jadefish** [comment]
```
> scripts/watch
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'npm@10.2.5',
npm WARN EBADENGINE   required: { node: '^18.17.0 || >=20.5.0' },
npm WARN EBADENGINE   current: { node: 'v16.17.0', npm: '9.4.0' }
npm WARN EBADENGINE }

up to date, audited 1135 packages in 3s

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
rbenv: foreman: command not found

The `foreman' command exists in these Ruby versions:
```

looks like we need foreman in the Gemfile for dev, too. (or gemspec?)


also: the `bundle.css` diff looks unminified now – did we lose CSS minification?

**Comment by danbee** [comment]
@jadefish We don't need (or should have) foreman in the Gemfile, it just needs to be installed for whatever Ruby version you're using.

**Comment by danbee** [comment]
@jadefish Yeah, I didn't tell sass to minify the CSS. I think that should be the concern of the project using the gem. I can change that though if you disagree.

**Comment by jadefish** [comment]
> @jadefish Yeah, I didn't tell sass to minify the CSS. I think that should be the concern of the project using the gem. I can change that though if you disagree.

not necessarily, but here it's a significant change, don't you think? (I'm hesitant to call it "breaking", but it does seem impactful.)

how would you envision us minifying in e.g. the core service?

**Comment by danbee** [comment]
@jadefish That's a reasonable point. I think what I said is true for gems providing assets to the asset pipeline, but I'm not sure that's the case here, so I'm going to switch on minimization.

**Comment by jadefish** [comment]
> @jadefish That's a reasonable point. I think what I said is true for gems providing assets to the asset pipeline, but I'm not sure that's the case here, so I'm going to switch on minimization.

yeah, bundle.css is (unfortunately) currently just linked to as-is in [`views/mdc/layout.erb`](https://github.com/coprl/coprl/blob/e0d70758f0f276f1fc071786c53ee53f8e86f4bf/views/mdc/layout.erb#L16). integration with the asset pipeline would be ideal (though maybe in a plugin since COPRL itself doesn't assume Rails is present).

**Review by jadefish — APPROVED** [review]

**Pull request merged**
